package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"puzzlr.gg/src/server/graphql/models"
	"puzzlr.gg/src/server/reqctx"
)

// AcceptFriendRequest is the resolver for the acceptFriendRequest field.
func (r *mutationResolver) AcceptFriendRequest(ctx context.Context, input models.AcceptFriendRequestInput) (models.AcceptFriendRequestResult, error) {
	userID, err := reqctx.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	friend, err := r.FriendshipService.AcceptFriendRequest(ctx, userID, input.SenderID)
	if err != nil {
		return nil, err
	}

	return &models.AcceptFriendRequestSuccess{
		Friend: friend,
	}, nil
}
