package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"puzzlr.gg/src/server/db/ent/codegen"
	graphql1 "puzzlr.gg/src/server/graphql/generated"
	"puzzlr.gg/src/server/graphql/models"
	"puzzlr.gg/src/server/reqctx"
)

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input *models.CreateGameInput) (*codegen.Game, error) {
	if input.TicTacToeInput != nil {
		userId, err := reqctx.UserIDFromContext(ctx)
		if err != nil {
			return nil, err
		}
		return r.GameService.CreateTicTacToeGame(ctx, userId, input.TicTacToeInput.OpponentID)
	}
	return nil, fmt.Errorf("unsupported game type")
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
