package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"puzzlr.gg/src/server/db/ent/codegen"
	"puzzlr.gg/src/server/graphql/models"
	"puzzlr.gg/src/server/reqctx"
)

// MakeGameMove is the resolver for the makeGameMove field.
func (r *mutationResolver) MakeGameMove(ctx context.Context, input models.MakeGameMoveInput) (*codegen.Game, error) {
	userID, err := reqctx.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	if input.Move.TicTacToeMove != nil {
		return r.GameService.MakeTicTacToeMove(
			ctx,
			input.GameID,
			userID, input.Move.TicTacToeMove.Row,
			input.Move.TicTacToeMove.Col,
		)
	}
	return nil, fmt.Errorf("unsupported game type")
}
