package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"puzzlr.gg/src/server/graphql/models"
	"puzzlr.gg/src/server/reqctx"
)

// RespondToFriendRequest is the resolver for the respondToFriendRequest field.
func (r *mutationResolver) RespondToFriendRequest(ctx context.Context, input models.RespondToFriendRequestInput) (models.RespondToFriendRequestResult, error) {
	userID, err := reqctx.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	sender, err := r.FriendshipService.RespondToFriendRequest(ctx, userID, input.SenderID, input.Accept)
	if err != nil {
		return nil, err
	}

	return &models.RespondToFriendRequestSuccess{
		Sender: sender,
	}, nil
}
