package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"puzzlr.gg/src/server/graphql/models"
)

// Gameboard is the resolver for the gameboard field.
func (r *queryResolver) Gameboard(ctx context.Context) (*models.GameBoard, error) {
	panic(fmt.Errorf("not implemented: Gameboard - gameboard"))
}
