package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"puzzlr.gg/src/server/graphql/models"
	"puzzlr.gg/src/server/reqctx"
)

// SendFriendRequest is the resolver for the sendFriendRequest field.
func (r *mutationResolver) SendFriendRequest(ctx context.Context, input models.SendFriendRequestInput) (models.SendFriendRequestResult, error) {
	userID, err := reqctx.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	friendRequest, err := r.FriendshipService.CreateFriendRequest(ctx, userID, input.RecipientID)
	if err != nil {
		return nil, err
	}

	recipient, err := r.Ent.User.Get(ctx, friendRequest.RecipientID)
	if err != nil {
		return nil, err
	}

	return &models.SendFriendRequestSuccess{
		Recipient: recipient,
	}, nil
}
