package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"puzzlr.gg/src/server/db/ent/codegen"
	"puzzlr.gg/src/server/graphql/models"
	"puzzlr.gg/src/server/reqctx"
)

// ViewerFriendshipStatus is the resolver for the viewerFriendshipStatus field.
func (r *userResolver) ViewerFriendshipStatus(ctx context.Context, obj *codegen.User) (models.ViewerFriendshipStatus, error) {
	viewerID, err := reqctx.UserIDFromContext(ctx)
	if err != nil {
		return models.ViewerFriendshipStatusNotLoggedIn, nil
	}

	if viewerID == obj.ID {
		return models.ViewerFriendshipStatusNotApplicable, nil
	}

	return r.FriendshipService.GetViewerFriendshipStatus(ctx, viewerID, obj.ID)
}
