// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"puzzlr.gg/src/server/db/ent/codegen"
)

type AcceptFriendRequestResult interface {
	IsAcceptFriendRequestResult()
}

type SendFriendRequestResult interface {
	IsSendFriendRequestResult()
}

type SidebarItem interface {
	IsSidebarItem()
}

type AcceptFriendRequestError struct {
	Message string `json:"message"`
}

func (AcceptFriendRequestError) IsAcceptFriendRequestResult() {}

type AcceptFriendRequestInput struct {
	SenderID int `json:"senderID"`
}

type AcceptFriendRequestSuccess struct {
	Friend *codegen.User `json:"friend"`
}

func (AcceptFriendRequestSuccess) IsAcceptFriendRequestResult() {}

type CreateGameInput struct {
	TicTacToeInput *CreateTicTacToeInput `json:"ticTacToeInput"`
}

type CreateTicTacToeInput struct {
	OpponentID int `json:"opponentId"`
}

type GameBoard struct {
	Rows []*GameBoardRow `json:"rows"`
}

type GameBoardRow struct {
	Elements []*string `json:"elements"`
}

type GameMoveInput struct {
	TicTacToeMove *TicTacToeMoveInput `json:"ticTacToeMove"`
}

type Link struct {
	Href     string `json:"href"`
	External bool   `json:"external"`
}

type MakeGameMoveInput struct {
	GameID int            `json:"gameId"`
	Move   *GameMoveInput `json:"move"`
}

type SendFriendRequestError struct {
	Message string `json:"message"`
}

func (SendFriendRequestError) IsSendFriendRequestResult() {}

type SendFriendRequestInput struct {
	RecipientID int `json:"recipientID"`
}

type SendFriendRequestSuccess struct {
	Recipient *codegen.User `json:"recipient"`
}

func (SendFriendRequestSuccess) IsSendFriendRequestResult() {}

type SidebarFolder struct {
	Name     string        `json:"name"`
	Children []SidebarItem `json:"children"`
}

func (SidebarFolder) IsSidebarItem() {}

type SidebarLink struct {
	Name string `json:"name"`
	Link *Link  `json:"link"`
}

func (SidebarLink) IsSidebarItem() {}

type TicTacToeMoveInput struct {
	Row int `json:"row"`
	Col int `json:"col"`
}

type ViewerFriendshipStatus string

const (
	ViewerFriendshipStatusFriends         ViewerFriendshipStatus = "FRIENDS"
	ViewerFriendshipStatusRequestSent     ViewerFriendshipStatus = "REQUEST_SENT"
	ViewerFriendshipStatusRequestReceived ViewerFriendshipStatus = "REQUEST_RECEIVED"
	ViewerFriendshipStatusNotFriends      ViewerFriendshipStatus = "NOT_FRIENDS"
	ViewerFriendshipStatusNotLoggedIn     ViewerFriendshipStatus = "NOT_LOGGED_IN"
	ViewerFriendshipStatusNotApplicable   ViewerFriendshipStatus = "NOT_APPLICABLE"
)

var AllViewerFriendshipStatus = []ViewerFriendshipStatus{
	ViewerFriendshipStatusFriends,
	ViewerFriendshipStatusRequestSent,
	ViewerFriendshipStatusRequestReceived,
	ViewerFriendshipStatusNotFriends,
	ViewerFriendshipStatusNotLoggedIn,
	ViewerFriendshipStatusNotApplicable,
}

func (e ViewerFriendshipStatus) IsValid() bool {
	switch e {
	case ViewerFriendshipStatusFriends, ViewerFriendshipStatusRequestSent, ViewerFriendshipStatusRequestReceived, ViewerFriendshipStatusNotFriends, ViewerFriendshipStatusNotLoggedIn, ViewerFriendshipStatusNotApplicable:
		return true
	}
	return false
}

func (e ViewerFriendshipStatus) String() string {
	return string(e)
}

func (e *ViewerFriendshipStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ViewerFriendshipStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ViewerFriendshipStatus", str)
	}
	return nil
}

func (e ViewerFriendshipStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ViewerFriendshipStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ViewerFriendshipStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
