// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"puzzlr.gg/src/server/db/ent/codegen"
)

type SendFriendRequestResult interface {
	IsSendFriendRequestResult()
}

type SidebarItem interface {
	IsSidebarItem()
}

type CreateGameInput struct {
	TicTacToeInput *CreateTicTacToeInput `json:"ticTacToeInput"`
}

type CreateTicTacToeInput struct {
	OpponentID int `json:"opponentId"`
}

type GameBoard struct {
	Rows []*GameBoardRow `json:"rows"`
}

type GameBoardRow struct {
	Elements []*string `json:"elements"`
}

type GameMoveInput struct {
	TicTacToeMove *TicTacToeMoveInput `json:"ticTacToeMove"`
}

type Link struct {
	Href     string `json:"href"`
	External bool   `json:"external"`
}

type MakeGameMoveInput struct {
	GameID int            `json:"gameId"`
	Move   *GameMoveInput `json:"move"`
}

type SendFriendRequestError struct {
	Message string `json:"message"`
}

func (SendFriendRequestError) IsSendFriendRequestResult() {}

type SendFriendRequestInput struct {
	RecipientID int `json:"recipientID"`
}

type SendFriendRequestSuccess struct {
	Recipient *codegen.User `json:"recipient"`
}

func (SendFriendRequestSuccess) IsSendFriendRequestResult() {}

type SidebarFolder struct {
	Name     string        `json:"name"`
	Children []SidebarItem `json:"children"`
}

func (SidebarFolder) IsSidebarItem() {}

type SidebarLink struct {
	Name string `json:"name"`
	Link *Link  `json:"link"`
}

func (SidebarLink) IsSidebarItem() {}

type TicTacToeMoveInput struct {
	Row int `json:"row"`
	Col int `json:"col"`
}
