// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"puzzlr.gg/src/server/db/ent/codegen/game"
	"puzzlr.gg/src/server/db/ent/codegen/gameplayer"
	"puzzlr.gg/src/server/db/ent/codegen/user"
)

// GameCreate is the builder for creating a Game entity.
type GameCreate struct {
	config
	mutation *GameMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *GameCreate) SetCreateTime(v time.Time) *GameCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *GameCreate) SetNillableCreateTime(v *time.Time) *GameCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *GameCreate) SetUpdateTime(v time.Time) *GameCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *GameCreate) SetNillableUpdateTime(v *time.Time) *GameCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *GameCreate) SetType(v game.Type) *GameCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetBoard sets the "board" field.
func (_c *GameCreate) SetBoard(v [][]string) *GameCreate {
	_c.mutation.SetBoard(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *GameCreate) SetMetadata(v json.RawMessage) *GameCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_c *GameCreate) AddUserIDs(ids ...int) *GameCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUser adds the "user" edges to the User entity.
func (_c *GameCreate) AddUser(v ...*User) *GameCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// SetWinnerID sets the "winner" edge to the User entity by ID.
func (_c *GameCreate) SetWinnerID(id int) *GameCreate {
	_c.mutation.SetWinnerID(id)
	return _c
}

// SetNillableWinnerID sets the "winner" edge to the User entity by ID if the given value is not nil.
func (_c *GameCreate) SetNillableWinnerID(id *int) *GameCreate {
	if id != nil {
		_c = _c.SetWinnerID(*id)
	}
	return _c
}

// SetWinner sets the "winner" edge to the User entity.
func (_c *GameCreate) SetWinner(v *User) *GameCreate {
	return _c.SetWinnerID(v.ID)
}

// SetCurrentTurnID sets the "current_turn" edge to the User entity by ID.
func (_c *GameCreate) SetCurrentTurnID(id int) *GameCreate {
	_c.mutation.SetCurrentTurnID(id)
	return _c
}

// SetNillableCurrentTurnID sets the "current_turn" edge to the User entity by ID if the given value is not nil.
func (_c *GameCreate) SetNillableCurrentTurnID(id *int) *GameCreate {
	if id != nil {
		_c = _c.SetCurrentTurnID(*id)
	}
	return _c
}

// SetCurrentTurn sets the "current_turn" edge to the User entity.
func (_c *GameCreate) SetCurrentTurn(v *User) *GameCreate {
	return _c.SetCurrentTurnID(v.ID)
}

// AddGamePlayerIDs adds the "game_player" edge to the GamePlayer entity by IDs.
func (_c *GameCreate) AddGamePlayerIDs(ids ...int) *GameCreate {
	_c.mutation.AddGamePlayerIDs(ids...)
	return _c
}

// AddGamePlayer adds the "game_player" edges to the GamePlayer entity.
func (_c *GameCreate) AddGamePlayer(v ...*GamePlayer) *GameCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGamePlayerIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_c *GameCreate) Mutation() *GameMutation {
	return _c.mutation
}

// Save creates the Game in the database.
func (_c *GameCreate) Save(ctx context.Context) (*Game, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GameCreate) SaveX(ctx context.Context) *Game {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GameCreate) defaults() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		if game.DefaultCreateTime == nil {
			return fmt.Errorf("codegen: uninitialized game.DefaultCreateTime (forgotten import codegen/runtime?)")
		}
		v := game.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		if game.DefaultUpdateTime == nil {
			return fmt.Errorf("codegen: uninitialized game.DefaultUpdateTime (forgotten import codegen/runtime?)")
		}
		v := game.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *GameCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`codegen: missing required field "Game.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`codegen: missing required field "Game.update_time"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`codegen: missing required field "Game.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := game.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`codegen: validator failed for field "Game.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Board(); !ok {
		return &ValidationError{Name: "board", err: errors.New(`codegen: missing required field "Game.board"`)}
	}
	return nil
}

func (_c *GameCreate) sqlSave(ctx context.Context) (*Game, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GameCreate) createSpec() (*Game, *sqlgraph.CreateSpec) {
	var (
		_node = &Game{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(game.Table, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(game.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(game.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(game.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Board(); ok {
		_spec.SetField(game.FieldBoard, field.TypeJSON, value)
		_node.Board = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(game.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WinnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.WinnerTable,
			Columns: []string{game.WinnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_won_games = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CurrentTurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.CurrentTurnTable,
			Columns: []string{game.CurrentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_current_turn_games = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GamePlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.GamePlayerTable,
			Columns: []string{game.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GameCreateBulk is the builder for creating many Game entities in bulk.
type GameCreateBulk struct {
	config
	err      error
	builders []*GameCreate
}

// Save creates the Game entities in the database.
func (_c *GameCreateBulk) Save(ctx context.Context) ([]*Game, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Game, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GameCreateBulk) SaveX(ctx context.Context) []*Game {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
