// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"puzzlr.gg/src/server/db/ent/codegen/game"
	"puzzlr.gg/src/server/db/ent/codegen/gameplayer"
	"puzzlr.gg/src/server/db/ent/codegen/predicate"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *GameUpdate) SetUpdateTime(v time.Time) *GameUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetBoard sets the "board" field.
func (_u *GameUpdate) SetBoard(v [][]string) *GameUpdate {
	_u.mutation.SetBoard(v)
	return _u
}

// AppendBoard appends value to the "board" field.
func (_u *GameUpdate) AppendBoard(v [][]string) *GameUpdate {
	_u.mutation.AppendBoard(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *GameUpdate) SetMetadata(v json.RawMessage) *GameUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *GameUpdate) AppendMetadata(v json.RawMessage) *GameUpdate {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *GameUpdate) ClearMetadata() *GameUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetWinnerPlayerID sets the "winner_player_id" field.
func (_u *GameUpdate) SetWinnerPlayerID(v int) *GameUpdate {
	_u.mutation.SetWinnerPlayerID(v)
	return _u
}

// SetNillableWinnerPlayerID sets the "winner_player_id" field if the given value is not nil.
func (_u *GameUpdate) SetNillableWinnerPlayerID(v *int) *GameUpdate {
	if v != nil {
		_u.SetWinnerPlayerID(*v)
	}
	return _u
}

// ClearWinnerPlayerID clears the value of the "winner_player_id" field.
func (_u *GameUpdate) ClearWinnerPlayerID() *GameUpdate {
	_u.mutation.ClearWinnerPlayerID()
	return _u
}

// SetCurrentTurnPlayerID sets the "current_turn_player_id" field.
func (_u *GameUpdate) SetCurrentTurnPlayerID(v int) *GameUpdate {
	_u.mutation.SetCurrentTurnPlayerID(v)
	return _u
}

// SetNillableCurrentTurnPlayerID sets the "current_turn_player_id" field if the given value is not nil.
func (_u *GameUpdate) SetNillableCurrentTurnPlayerID(v *int) *GameUpdate {
	if v != nil {
		_u.SetCurrentTurnPlayerID(*v)
	}
	return _u
}

// ClearCurrentTurnPlayerID clears the value of the "current_turn_player_id" field.
func (_u *GameUpdate) ClearCurrentTurnPlayerID() *GameUpdate {
	_u.mutation.ClearCurrentTurnPlayerID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *GameUpdate) SetStatus(v game.Status) *GameUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameUpdate) SetNillableStatus(v *game.Status) *GameUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddPlayerIDs adds the "players" edge to the GamePlayer entity by IDs.
func (_u *GameUpdate) AddPlayerIDs(ids ...int) *GameUpdate {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the GamePlayer entity.
func (_u *GameUpdate) AddPlayers(v ...*GamePlayer) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// SetWinnerPlayer sets the "winner_player" edge to the GamePlayer entity.
func (_u *GameUpdate) SetWinnerPlayer(v *GamePlayer) *GameUpdate {
	return _u.SetWinnerPlayerID(v.ID)
}

// SetCurrentTurnPlayer sets the "current_turn_player" edge to the GamePlayer entity.
func (_u *GameUpdate) SetCurrentTurnPlayer(v *GamePlayer) *GameUpdate {
	return _u.SetCurrentTurnPlayerID(v.ID)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the GamePlayer entity.
func (_u *GameUpdate) ClearPlayers() *GameUpdate {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to GamePlayer entities by IDs.
func (_u *GameUpdate) RemovePlayerIDs(ids ...int) *GameUpdate {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to GamePlayer entities.
func (_u *GameUpdate) RemovePlayers(v ...*GamePlayer) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearWinnerPlayer clears the "winner_player" edge to the GamePlayer entity.
func (_u *GameUpdate) ClearWinnerPlayer() *GameUpdate {
	_u.mutation.ClearWinnerPlayer()
	return _u
}

// ClearCurrentTurnPlayer clears the "current_turn_player" edge to the GamePlayer entity.
func (_u *GameUpdate) ClearCurrentTurnPlayer() *GameUpdate {
	_u.mutation.ClearCurrentTurnPlayer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if game.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("codegen: uninitialized game.UpdateDefaultUpdateTime (forgotten import codegen/runtime?)")
		}
		v := game.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := game.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`codegen: validator failed for field "Game.status": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(game.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Board(); ok {
		_spec.SetField(game.FieldBoard, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBoard(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldBoard, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(game.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(game.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(game.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WinnerPlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.WinnerPlayerTable,
			Columns: []string{game.WinnerPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WinnerPlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.WinnerPlayerTable,
			Columns: []string{game.WinnerPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentTurnPlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.CurrentTurnPlayerTable,
			Columns: []string{game.CurrentTurnPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentTurnPlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.CurrentTurnPlayerTable,
			Columns: []string{game.CurrentTurnPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *GameUpdateOne) SetUpdateTime(v time.Time) *GameUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetBoard sets the "board" field.
func (_u *GameUpdateOne) SetBoard(v [][]string) *GameUpdateOne {
	_u.mutation.SetBoard(v)
	return _u
}

// AppendBoard appends value to the "board" field.
func (_u *GameUpdateOne) AppendBoard(v [][]string) *GameUpdateOne {
	_u.mutation.AppendBoard(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *GameUpdateOne) SetMetadata(v json.RawMessage) *GameUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *GameUpdateOne) AppendMetadata(v json.RawMessage) *GameUpdateOne {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *GameUpdateOne) ClearMetadata() *GameUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetWinnerPlayerID sets the "winner_player_id" field.
func (_u *GameUpdateOne) SetWinnerPlayerID(v int) *GameUpdateOne {
	_u.mutation.SetWinnerPlayerID(v)
	return _u
}

// SetNillableWinnerPlayerID sets the "winner_player_id" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableWinnerPlayerID(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetWinnerPlayerID(*v)
	}
	return _u
}

// ClearWinnerPlayerID clears the value of the "winner_player_id" field.
func (_u *GameUpdateOne) ClearWinnerPlayerID() *GameUpdateOne {
	_u.mutation.ClearWinnerPlayerID()
	return _u
}

// SetCurrentTurnPlayerID sets the "current_turn_player_id" field.
func (_u *GameUpdateOne) SetCurrentTurnPlayerID(v int) *GameUpdateOne {
	_u.mutation.SetCurrentTurnPlayerID(v)
	return _u
}

// SetNillableCurrentTurnPlayerID sets the "current_turn_player_id" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableCurrentTurnPlayerID(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetCurrentTurnPlayerID(*v)
	}
	return _u
}

// ClearCurrentTurnPlayerID clears the value of the "current_turn_player_id" field.
func (_u *GameUpdateOne) ClearCurrentTurnPlayerID() *GameUpdateOne {
	_u.mutation.ClearCurrentTurnPlayerID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *GameUpdateOne) SetStatus(v game.Status) *GameUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableStatus(v *game.Status) *GameUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddPlayerIDs adds the "players" edge to the GamePlayer entity by IDs.
func (_u *GameUpdateOne) AddPlayerIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the GamePlayer entity.
func (_u *GameUpdateOne) AddPlayers(v ...*GamePlayer) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// SetWinnerPlayer sets the "winner_player" edge to the GamePlayer entity.
func (_u *GameUpdateOne) SetWinnerPlayer(v *GamePlayer) *GameUpdateOne {
	return _u.SetWinnerPlayerID(v.ID)
}

// SetCurrentTurnPlayer sets the "current_turn_player" edge to the GamePlayer entity.
func (_u *GameUpdateOne) SetCurrentTurnPlayer(v *GamePlayer) *GameUpdateOne {
	return _u.SetCurrentTurnPlayerID(v.ID)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the GamePlayer entity.
func (_u *GameUpdateOne) ClearPlayers() *GameUpdateOne {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to GamePlayer entities by IDs.
func (_u *GameUpdateOne) RemovePlayerIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to GamePlayer entities.
func (_u *GameUpdateOne) RemovePlayers(v ...*GamePlayer) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearWinnerPlayer clears the "winner_player" edge to the GamePlayer entity.
func (_u *GameUpdateOne) ClearWinnerPlayer() *GameUpdateOne {
	_u.mutation.ClearWinnerPlayer()
	return _u
}

// ClearCurrentTurnPlayer clears the "current_turn_player" edge to the GamePlayer entity.
func (_u *GameUpdateOne) ClearCurrentTurnPlayer() *GameUpdateOne {
	_u.mutation.ClearCurrentTurnPlayer()
	return _u
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if game.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("codegen: uninitialized game.UpdateDefaultUpdateTime (forgotten import codegen/runtime?)")
		}
		v := game.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := game.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`codegen: validator failed for field "Game.status": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`codegen: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("codegen: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(game.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Board(); ok {
		_spec.SetField(game.FieldBoard, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBoard(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldBoard, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(game.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(game.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(game.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WinnerPlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.WinnerPlayerTable,
			Columns: []string{game.WinnerPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WinnerPlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.WinnerPlayerTable,
			Columns: []string{game.WinnerPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentTurnPlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.CurrentTurnPlayerTable,
			Columns: []string{game.CurrentTurnPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentTurnPlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   game.CurrentTurnPlayerTable,
			Columns: []string{game.CurrentTurnPlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
