// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"puzzlr.gg/src/server/db/ent/codegen/game"
	"puzzlr.gg/src/server/db/ent/codegen/gameplayer"
)

// Game is the model entity for the Game schema.
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Type holds the value of the "type" field.
	Type game.Type `json:"type,omitempty"`
	// Board holds the value of the "board" field.
	Board [][]string `json:"board,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata json.RawMessage `json:"metadata,omitempty"`
	// WinnerPlayerID holds the value of the "winner_player_id" field.
	WinnerPlayerID *int `json:"winner_player_id,omitempty"`
	// CurrentTurnPlayerID holds the value of the "current_turn_player_id" field.
	CurrentTurnPlayerID *int `json:"current_turn_player_id,omitempty"`
	// Status holds the value of the "status" field.
	Status game.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameQuery when eager-loading is set.
	Edges        GameEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GameEdges holds the relations/edges for other nodes in the graph.
type GameEdges struct {
	// Players holds the value of the players edge.
	Players []*GamePlayer `json:"players,omitempty"`
	// WinnerPlayer holds the value of the winner_player edge.
	WinnerPlayer *GamePlayer `json:"winner_player,omitempty"`
	// CurrentTurnPlayer holds the value of the current_turn_player edge.
	CurrentTurnPlayer *GamePlayer `json:"current_turn_player,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int

	namedPlayers map[string][]*GamePlayer
}

// PlayersOrErr returns the Players value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) PlayersOrErr() ([]*GamePlayer, error) {
	if e.loadedTypes[0] {
		return e.Players, nil
	}
	return nil, &NotLoadedError{edge: "players"}
}

// WinnerPlayerOrErr returns the WinnerPlayer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEdges) WinnerPlayerOrErr() (*GamePlayer, error) {
	if e.WinnerPlayer != nil {
		return e.WinnerPlayer, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: gameplayer.Label}
	}
	return nil, &NotLoadedError{edge: "winner_player"}
}

// CurrentTurnPlayerOrErr returns the CurrentTurnPlayer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEdges) CurrentTurnPlayerOrErr() (*GamePlayer, error) {
	if e.CurrentTurnPlayer != nil {
		return e.CurrentTurnPlayer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: gameplayer.Label}
	}
	return nil, &NotLoadedError{edge: "current_turn_player"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldBoard, game.FieldMetadata:
			values[i] = new([]byte)
		case game.FieldID, game.FieldWinnerPlayerID, game.FieldCurrentTurnPlayerID:
			values[i] = new(sql.NullInt64)
		case game.FieldType, game.FieldStatus:
			values[i] = new(sql.NullString)
		case game.FieldCreateTime, game.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (_m *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case game.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case game.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case game.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = game.Type(value.String)
			}
		case game.FieldBoard:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field board", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Board); err != nil {
					return fmt.Errorf("unmarshal field board: %w", err)
				}
			}
		case game.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case game.FieldWinnerPlayerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field winner_player_id", values[i])
			} else if value.Valid {
				_m.WinnerPlayerID = new(int)
				*_m.WinnerPlayerID = int(value.Int64)
			}
		case game.FieldCurrentTurnPlayerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_turn_player_id", values[i])
			} else if value.Valid {
				_m.CurrentTurnPlayerID = new(int)
				*_m.CurrentTurnPlayerID = int(value.Int64)
			}
		case game.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = game.Status(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (_m *Game) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlayers queries the "players" edge of the Game entity.
func (_m *Game) QueryPlayers() *GamePlayerQuery {
	return NewGameClient(_m.config).QueryPlayers(_m)
}

// QueryWinnerPlayer queries the "winner_player" edge of the Game entity.
func (_m *Game) QueryWinnerPlayer() *GamePlayerQuery {
	return NewGameClient(_m.config).QueryWinnerPlayer(_m)
}

// QueryCurrentTurnPlayer queries the "current_turn_player" edge of the Game entity.
func (_m *Game) QueryCurrentTurnPlayer() *GamePlayerQuery {
	return NewGameClient(_m.config).QueryCurrentTurnPlayer(_m)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Game) Update() *GameUpdateOne {
	return NewGameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Game) Unwrap() *Game {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("codegen: Game is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("board=")
	builder.WriteString(fmt.Sprintf("%v", _m.Board))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.WinnerPlayerID; v != nil {
		builder.WriteString("winner_player_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CurrentTurnPlayerID; v != nil {
		builder.WriteString("current_turn_player_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// NamedPlayers returns the Players named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Game) NamedPlayers(name string) ([]*GamePlayer, error) {
	if _m.Edges.namedPlayers == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedPlayers[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Game) appendNamedPlayers(name string, edges ...*GamePlayer) {
	if _m.Edges.namedPlayers == nil {
		_m.Edges.namedPlayers = make(map[string][]*GamePlayer)
	}
	if len(edges) == 0 {
		_m.Edges.namedPlayers[name] = []*GamePlayer{}
	} else {
		_m.Edges.namedPlayers[name] = append(_m.Edges.namedPlayers[name], edges...)
	}
}

// Games is a parsable slice of Game.
type Games []*Game
