// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"puzzlr.gg/src/server/db/ent/codegen/game"
	"puzzlr.gg/src/server/db/ent/codegen/gameplayer"
	"puzzlr.gg/src/server/db/ent/codegen/predicate"
	"puzzlr.gg/src/server/db/ent/codegen/user"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *GameUpdate) SetUpdateTime(v time.Time) *GameUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetBoard sets the "board" field.
func (_u *GameUpdate) SetBoard(v [][]string) *GameUpdate {
	_u.mutation.SetBoard(v)
	return _u
}

// AppendBoard appends value to the "board" field.
func (_u *GameUpdate) AppendBoard(v [][]string) *GameUpdate {
	_u.mutation.AppendBoard(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *GameUpdate) SetMetadata(v json.RawMessage) *GameUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *GameUpdate) AppendMetadata(v json.RawMessage) *GameUpdate {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *GameUpdate) ClearMetadata() *GameUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *GameUpdate) AddUserIDs(ids ...int) *GameUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *GameUpdate) AddUser(v ...*User) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// SetWinnerID sets the "winner" edge to the User entity by ID.
func (_u *GameUpdate) SetWinnerID(id int) *GameUpdate {
	_u.mutation.SetWinnerID(id)
	return _u
}

// SetNillableWinnerID sets the "winner" edge to the User entity by ID if the given value is not nil.
func (_u *GameUpdate) SetNillableWinnerID(id *int) *GameUpdate {
	if id != nil {
		_u = _u.SetWinnerID(*id)
	}
	return _u
}

// SetWinner sets the "winner" edge to the User entity.
func (_u *GameUpdate) SetWinner(v *User) *GameUpdate {
	return _u.SetWinnerID(v.ID)
}

// SetCurrentTurnID sets the "current_turn" edge to the User entity by ID.
func (_u *GameUpdate) SetCurrentTurnID(id int) *GameUpdate {
	_u.mutation.SetCurrentTurnID(id)
	return _u
}

// SetNillableCurrentTurnID sets the "current_turn" edge to the User entity by ID if the given value is not nil.
func (_u *GameUpdate) SetNillableCurrentTurnID(id *int) *GameUpdate {
	if id != nil {
		_u = _u.SetCurrentTurnID(*id)
	}
	return _u
}

// SetCurrentTurn sets the "current_turn" edge to the User entity.
func (_u *GameUpdate) SetCurrentTurn(v *User) *GameUpdate {
	return _u.SetCurrentTurnID(v.ID)
}

// AddGamePlayerIDs adds the "game_player" edge to the GamePlayer entity by IDs.
func (_u *GameUpdate) AddGamePlayerIDs(ids ...int) *GameUpdate {
	_u.mutation.AddGamePlayerIDs(ids...)
	return _u
}

// AddGamePlayer adds the "game_player" edges to the GamePlayer entity.
func (_u *GameUpdate) AddGamePlayer(v ...*GamePlayer) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGamePlayerIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *GameUpdate) ClearUser() *GameUpdate {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *GameUpdate) RemoveUserIDs(ids ...int) *GameUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *GameUpdate) RemoveUser(v ...*User) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearWinner clears the "winner" edge to the User entity.
func (_u *GameUpdate) ClearWinner() *GameUpdate {
	_u.mutation.ClearWinner()
	return _u
}

// ClearCurrentTurn clears the "current_turn" edge to the User entity.
func (_u *GameUpdate) ClearCurrentTurn() *GameUpdate {
	_u.mutation.ClearCurrentTurn()
	return _u
}

// ClearGamePlayer clears all "game_player" edges to the GamePlayer entity.
func (_u *GameUpdate) ClearGamePlayer() *GameUpdate {
	_u.mutation.ClearGamePlayer()
	return _u
}

// RemoveGamePlayerIDs removes the "game_player" edge to GamePlayer entities by IDs.
func (_u *GameUpdate) RemoveGamePlayerIDs(ids ...int) *GameUpdate {
	_u.mutation.RemoveGamePlayerIDs(ids...)
	return _u
}

// RemoveGamePlayer removes "game_player" edges to GamePlayer entities.
func (_u *GameUpdate) RemoveGamePlayer(v ...*GamePlayer) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGamePlayerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if game.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("codegen: uninitialized game.UpdateDefaultUpdateTime (forgotten import codegen/runtime?)")
		}
		v := game.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(game.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Board(); ok {
		_spec.SetField(game.FieldBoard, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBoard(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldBoard, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(game.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(game.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WinnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.WinnerTable,
			Columns: []string{game.WinnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WinnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.WinnerTable,
			Columns: []string{game.WinnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentTurnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.CurrentTurnTable,
			Columns: []string{game.CurrentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentTurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.CurrentTurnTable,
			Columns: []string{game.CurrentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.GamePlayerTable,
			Columns: []string{game.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamePlayerIDs(); len(nodes) > 0 && !_u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.GamePlayerTable,
			Columns: []string{game.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamePlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.GamePlayerTable,
			Columns: []string{game.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *GameUpdateOne) SetUpdateTime(v time.Time) *GameUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetBoard sets the "board" field.
func (_u *GameUpdateOne) SetBoard(v [][]string) *GameUpdateOne {
	_u.mutation.SetBoard(v)
	return _u
}

// AppendBoard appends value to the "board" field.
func (_u *GameUpdateOne) AppendBoard(v [][]string) *GameUpdateOne {
	_u.mutation.AppendBoard(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *GameUpdateOne) SetMetadata(v json.RawMessage) *GameUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *GameUpdateOne) AppendMetadata(v json.RawMessage) *GameUpdateOne {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *GameUpdateOne) ClearMetadata() *GameUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *GameUpdateOne) AddUserIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *GameUpdateOne) AddUser(v ...*User) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// SetWinnerID sets the "winner" edge to the User entity by ID.
func (_u *GameUpdateOne) SetWinnerID(id int) *GameUpdateOne {
	_u.mutation.SetWinnerID(id)
	return _u
}

// SetNillableWinnerID sets the "winner" edge to the User entity by ID if the given value is not nil.
func (_u *GameUpdateOne) SetNillableWinnerID(id *int) *GameUpdateOne {
	if id != nil {
		_u = _u.SetWinnerID(*id)
	}
	return _u
}

// SetWinner sets the "winner" edge to the User entity.
func (_u *GameUpdateOne) SetWinner(v *User) *GameUpdateOne {
	return _u.SetWinnerID(v.ID)
}

// SetCurrentTurnID sets the "current_turn" edge to the User entity by ID.
func (_u *GameUpdateOne) SetCurrentTurnID(id int) *GameUpdateOne {
	_u.mutation.SetCurrentTurnID(id)
	return _u
}

// SetNillableCurrentTurnID sets the "current_turn" edge to the User entity by ID if the given value is not nil.
func (_u *GameUpdateOne) SetNillableCurrentTurnID(id *int) *GameUpdateOne {
	if id != nil {
		_u = _u.SetCurrentTurnID(*id)
	}
	return _u
}

// SetCurrentTurn sets the "current_turn" edge to the User entity.
func (_u *GameUpdateOne) SetCurrentTurn(v *User) *GameUpdateOne {
	return _u.SetCurrentTurnID(v.ID)
}

// AddGamePlayerIDs adds the "game_player" edge to the GamePlayer entity by IDs.
func (_u *GameUpdateOne) AddGamePlayerIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddGamePlayerIDs(ids...)
	return _u
}

// AddGamePlayer adds the "game_player" edges to the GamePlayer entity.
func (_u *GameUpdateOne) AddGamePlayer(v ...*GamePlayer) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGamePlayerIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *GameUpdateOne) ClearUser() *GameUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *GameUpdateOne) RemoveUserIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *GameUpdateOne) RemoveUser(v ...*User) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearWinner clears the "winner" edge to the User entity.
func (_u *GameUpdateOne) ClearWinner() *GameUpdateOne {
	_u.mutation.ClearWinner()
	return _u
}

// ClearCurrentTurn clears the "current_turn" edge to the User entity.
func (_u *GameUpdateOne) ClearCurrentTurn() *GameUpdateOne {
	_u.mutation.ClearCurrentTurn()
	return _u
}

// ClearGamePlayer clears all "game_player" edges to the GamePlayer entity.
func (_u *GameUpdateOne) ClearGamePlayer() *GameUpdateOne {
	_u.mutation.ClearGamePlayer()
	return _u
}

// RemoveGamePlayerIDs removes the "game_player" edge to GamePlayer entities by IDs.
func (_u *GameUpdateOne) RemoveGamePlayerIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemoveGamePlayerIDs(ids...)
	return _u
}

// RemoveGamePlayer removes "game_player" edges to GamePlayer entities.
func (_u *GameUpdateOne) RemoveGamePlayer(v ...*GamePlayer) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGamePlayerIDs(ids...)
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if game.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("codegen: uninitialized game.UpdateDefaultUpdateTime (forgotten import codegen/runtime?)")
		}
		v := game.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`codegen: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("codegen: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(game.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Board(); ok {
		_spec.SetField(game.FieldBoard, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBoard(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldBoard, value)
		})
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(game.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(game.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WinnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.WinnerTable,
			Columns: []string{game.WinnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WinnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.WinnerTable,
			Columns: []string{game.WinnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentTurnCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.CurrentTurnTable,
			Columns: []string{game.CurrentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentTurnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   game.CurrentTurnTable,
			Columns: []string{game.CurrentTurnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.GamePlayerTable,
			Columns: []string{game.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamePlayerIDs(); len(nodes) > 0 && !_u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.GamePlayerTable,
			Columns: []string{game.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamePlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   game.GamePlayerTable,
			Columns: []string{game.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
