// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Game) User(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUser(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UserOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().All(ctx)
	}
	return result, err
}

func (_m *Game) Winner(ctx context.Context) (*User, error) {
	result, err := _m.Edges.WinnerOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryWinner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Game) CurrentTurn(ctx context.Context) (*User, error) {
	result, err := _m.Edges.CurrentTurnOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCurrentTurn().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *User) Games(ctx context.Context) (result []*Game, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedGames(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.GamesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryGames().All(ctx)
	}
	return result, err
}
