// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"
)

func (ga *Game) PlayerOne(ctx context.Context) (*User, error) {
	result, err := ga.Edges.PlayerOneOrErr()
	if IsNotLoaded(err) {
		result, err = ga.QueryPlayerOne().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (ga *Game) PlayerTwo(ctx context.Context) (*User, error) {
	result, err := ga.Edges.PlayerTwoOrErr()
	if IsNotLoaded(err) {
		result, err = ga.QueryPlayerTwo().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (ga *Game) Winner(ctx context.Context) (*User, error) {
	result, err := ga.Edges.WinnerOrErr()
	if IsNotLoaded(err) {
		result, err = ga.QueryWinner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (ga *Game) CurrentTurn(ctx context.Context) (*User, error) {
	result, err := ga.Edges.CurrentTurnOrErr()
	if IsNotLoaded(err) {
		result, err = ga.QueryCurrentTurn().Only(ctx)
	}
	return result, MaskNotFound(err)
}
