// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Game) Players(ctx context.Context) (result []*GamePlayer, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPlayers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PlayersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPlayers().All(ctx)
	}
	return result, err
}

func (_m *Game) WinnerPlayer(ctx context.Context) (*GamePlayer, error) {
	result, err := _m.Edges.WinnerPlayerOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryWinnerPlayer().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Game) CurrentTurnPlayer(ctx context.Context) (*GamePlayer, error) {
	result, err := _m.Edges.CurrentTurnPlayerOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCurrentTurnPlayer().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *GamePlayer) User(ctx context.Context) (*User, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *User) Friends(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedFriends(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.FriendsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryFriends().All(ctx)
	}
	return result, err
}
