// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"errors"
	"fmt"
	"time"

	"puzzlr.gg/src/server/db/ent/codegen/game"
	"puzzlr.gg/src/server/db/ent/codegen/gameplayer"
	"puzzlr.gg/src/server/db/ent/codegen/predicate"
	"puzzlr.gg/src/server/db/ent/codegen/user"
)

// GameWhereInput represents a where input for filtering Game queries.
type GameWhereInput struct {
	Predicates []predicate.Game  `json:"-"`
	Not        *GameWhereInput   `json:"not,omitempty"`
	Or         []*GameWhereInput `json:"or,omitempty"`
	And        []*GameWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *int  `json:"id,omitempty"`
	IDNEQ   *int  `json:"idNEQ,omitempty"`
	IDIn    []int `json:"idIn,omitempty"`
	IDNotIn []int `json:"idNotIn,omitempty"`
	IDGT    *int  `json:"idGT,omitempty"`
	IDGTE   *int  `json:"idGTE,omitempty"`
	IDLT    *int  `json:"idLT,omitempty"`
	IDLTE   *int  `json:"idLTE,omitempty"`

	// "create_time" field predicates.
	CreateTime      *time.Time  `json:"createTime,omitempty"`
	CreateTimeNEQ   *time.Time  `json:"createTimeNEQ,omitempty"`
	CreateTimeIn    []time.Time `json:"createTimeIn,omitempty"`
	CreateTimeNotIn []time.Time `json:"createTimeNotIn,omitempty"`
	CreateTimeGT    *time.Time  `json:"createTimeGT,omitempty"`
	CreateTimeGTE   *time.Time  `json:"createTimeGTE,omitempty"`
	CreateTimeLT    *time.Time  `json:"createTimeLT,omitempty"`
	CreateTimeLTE   *time.Time  `json:"createTimeLTE,omitempty"`

	// "update_time" field predicates.
	UpdateTime      *time.Time  `json:"updateTime,omitempty"`
	UpdateTimeNEQ   *time.Time  `json:"updateTimeNEQ,omitempty"`
	UpdateTimeIn    []time.Time `json:"updateTimeIn,omitempty"`
	UpdateTimeNotIn []time.Time `json:"updateTimeNotIn,omitempty"`
	UpdateTimeGT    *time.Time  `json:"updateTimeGT,omitempty"`
	UpdateTimeGTE   *time.Time  `json:"updateTimeGTE,omitempty"`
	UpdateTimeLT    *time.Time  `json:"updateTimeLT,omitempty"`
	UpdateTimeLTE   *time.Time  `json:"updateTimeLTE,omitempty"`

	// "type" field predicates.
	Type      *game.Type  `json:"type,omitempty"`
	TypeNEQ   *game.Type  `json:"typeNEQ,omitempty"`
	TypeIn    []game.Type `json:"typeIn,omitempty"`
	TypeNotIn []game.Type `json:"typeNotIn,omitempty"`

	// "status" field predicates.
	Status      *game.Status  `json:"status,omitempty"`
	StatusNEQ   *game.Status  `json:"statusNEQ,omitempty"`
	StatusIn    []game.Status `json:"statusIn,omitempty"`
	StatusNotIn []game.Status `json:"statusNotIn,omitempty"`

	// "players" edge predicates.
	HasPlayers     *bool                   `json:"hasPlayers,omitempty"`
	HasPlayersWith []*GamePlayerWhereInput `json:"hasPlayersWith,omitempty"`

	// "winner_player" edge predicates.
	HasWinnerPlayer     *bool                   `json:"hasWinnerPlayer,omitempty"`
	HasWinnerPlayerWith []*GamePlayerWhereInput `json:"hasWinnerPlayerWith,omitempty"`

	// "current_turn_player" edge predicates.
	HasCurrentTurnPlayer     *bool                   `json:"hasCurrentTurnPlayer,omitempty"`
	HasCurrentTurnPlayerWith []*GamePlayerWhereInput `json:"hasCurrentTurnPlayerWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *GameWhereInput) AddPredicates(predicates ...predicate.Game) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the GameWhereInput filter on the GameQuery builder.
func (i *GameWhereInput) Filter(q *GameQuery) (*GameQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyGameWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyGameWhereInput is returned in case the GameWhereInput is empty.
var ErrEmptyGameWhereInput = errors.New("codegen: empty predicate GameWhereInput")

// P returns a predicate for filtering games.
// An error is returned if the input is empty or invalid.
func (i *GameWhereInput) P() (predicate.Game, error) {
	var predicates []predicate.Game
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, game.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Game, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, game.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Game, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, game.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, game.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, game.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, game.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, game.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, game.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, game.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, game.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, game.IDLTE(*i.IDLTE))
	}
	if i.CreateTime != nil {
		predicates = append(predicates, game.CreateTimeEQ(*i.CreateTime))
	}
	if i.CreateTimeNEQ != nil {
		predicates = append(predicates, game.CreateTimeNEQ(*i.CreateTimeNEQ))
	}
	if len(i.CreateTimeIn) > 0 {
		predicates = append(predicates, game.CreateTimeIn(i.CreateTimeIn...))
	}
	if len(i.CreateTimeNotIn) > 0 {
		predicates = append(predicates, game.CreateTimeNotIn(i.CreateTimeNotIn...))
	}
	if i.CreateTimeGT != nil {
		predicates = append(predicates, game.CreateTimeGT(*i.CreateTimeGT))
	}
	if i.CreateTimeGTE != nil {
		predicates = append(predicates, game.CreateTimeGTE(*i.CreateTimeGTE))
	}
	if i.CreateTimeLT != nil {
		predicates = append(predicates, game.CreateTimeLT(*i.CreateTimeLT))
	}
	if i.CreateTimeLTE != nil {
		predicates = append(predicates, game.CreateTimeLTE(*i.CreateTimeLTE))
	}
	if i.UpdateTime != nil {
		predicates = append(predicates, game.UpdateTimeEQ(*i.UpdateTime))
	}
	if i.UpdateTimeNEQ != nil {
		predicates = append(predicates, game.UpdateTimeNEQ(*i.UpdateTimeNEQ))
	}
	if len(i.UpdateTimeIn) > 0 {
		predicates = append(predicates, game.UpdateTimeIn(i.UpdateTimeIn...))
	}
	if len(i.UpdateTimeNotIn) > 0 {
		predicates = append(predicates, game.UpdateTimeNotIn(i.UpdateTimeNotIn...))
	}
	if i.UpdateTimeGT != nil {
		predicates = append(predicates, game.UpdateTimeGT(*i.UpdateTimeGT))
	}
	if i.UpdateTimeGTE != nil {
		predicates = append(predicates, game.UpdateTimeGTE(*i.UpdateTimeGTE))
	}
	if i.UpdateTimeLT != nil {
		predicates = append(predicates, game.UpdateTimeLT(*i.UpdateTimeLT))
	}
	if i.UpdateTimeLTE != nil {
		predicates = append(predicates, game.UpdateTimeLTE(*i.UpdateTimeLTE))
	}
	if i.Type != nil {
		predicates = append(predicates, game.TypeEQ(*i.Type))
	}
	if i.TypeNEQ != nil {
		predicates = append(predicates, game.TypeNEQ(*i.TypeNEQ))
	}
	if len(i.TypeIn) > 0 {
		predicates = append(predicates, game.TypeIn(i.TypeIn...))
	}
	if len(i.TypeNotIn) > 0 {
		predicates = append(predicates, game.TypeNotIn(i.TypeNotIn...))
	}
	if i.Status != nil {
		predicates = append(predicates, game.StatusEQ(*i.Status))
	}
	if i.StatusNEQ != nil {
		predicates = append(predicates, game.StatusNEQ(*i.StatusNEQ))
	}
	if len(i.StatusIn) > 0 {
		predicates = append(predicates, game.StatusIn(i.StatusIn...))
	}
	if len(i.StatusNotIn) > 0 {
		predicates = append(predicates, game.StatusNotIn(i.StatusNotIn...))
	}

	if i.HasPlayers != nil {
		p := game.HasPlayers()
		if !*i.HasPlayers {
			p = game.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasPlayersWith) > 0 {
		with := make([]predicate.GamePlayer, 0, len(i.HasPlayersWith))
		for _, w := range i.HasPlayersWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasPlayersWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, game.HasPlayersWith(with...))
	}
	if i.HasWinnerPlayer != nil {
		p := game.HasWinnerPlayer()
		if !*i.HasWinnerPlayer {
			p = game.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasWinnerPlayerWith) > 0 {
		with := make([]predicate.GamePlayer, 0, len(i.HasWinnerPlayerWith))
		for _, w := range i.HasWinnerPlayerWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasWinnerPlayerWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, game.HasWinnerPlayerWith(with...))
	}
	if i.HasCurrentTurnPlayer != nil {
		p := game.HasCurrentTurnPlayer()
		if !*i.HasCurrentTurnPlayer {
			p = game.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasCurrentTurnPlayerWith) > 0 {
		with := make([]predicate.GamePlayer, 0, len(i.HasCurrentTurnPlayerWith))
		for _, w := range i.HasCurrentTurnPlayerWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasCurrentTurnPlayerWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, game.HasCurrentTurnPlayerWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyGameWhereInput
	case 1:
		return predicates[0], nil
	default:
		return game.And(predicates...), nil
	}
}

// GamePlayerWhereInput represents a where input for filtering GamePlayer queries.
type GamePlayerWhereInput struct {
	Predicates []predicate.GamePlayer  `json:"-"`
	Not        *GamePlayerWhereInput   `json:"not,omitempty"`
	Or         []*GamePlayerWhereInput `json:"or,omitempty"`
	And        []*GamePlayerWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *int  `json:"id,omitempty"`
	IDNEQ   *int  `json:"idNEQ,omitempty"`
	IDIn    []int `json:"idIn,omitempty"`
	IDNotIn []int `json:"idNotIn,omitempty"`
	IDGT    *int  `json:"idGT,omitempty"`
	IDGTE   *int  `json:"idGTE,omitempty"`
	IDLT    *int  `json:"idLT,omitempty"`
	IDLTE   *int  `json:"idLTE,omitempty"`

	// "kind" field predicates.
	Kind      *gameplayer.Kind  `json:"kind,omitempty"`
	KindNEQ   *gameplayer.Kind  `json:"kindNEQ,omitempty"`
	KindIn    []gameplayer.Kind `json:"kindIn,omitempty"`
	KindNotIn []gameplayer.Kind `json:"kindNotIn,omitempty"`

	// "marker" field predicates.
	Marker             *string  `json:"marker,omitempty"`
	MarkerNEQ          *string  `json:"markerNEQ,omitempty"`
	MarkerIn           []string `json:"markerIn,omitempty"`
	MarkerNotIn        []string `json:"markerNotIn,omitempty"`
	MarkerGT           *string  `json:"markerGT,omitempty"`
	MarkerGTE          *string  `json:"markerGTE,omitempty"`
	MarkerLT           *string  `json:"markerLT,omitempty"`
	MarkerLTE          *string  `json:"markerLTE,omitempty"`
	MarkerContains     *string  `json:"markerContains,omitempty"`
	MarkerHasPrefix    *string  `json:"markerHasPrefix,omitempty"`
	MarkerHasSuffix    *string  `json:"markerHasSuffix,omitempty"`
	MarkerEqualFold    *string  `json:"markerEqualFold,omitempty"`
	MarkerContainsFold *string  `json:"markerContainsFold,omitempty"`

	// "user" edge predicates.
	HasUser     *bool             `json:"hasUser,omitempty"`
	HasUserWith []*UserWhereInput `json:"hasUserWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *GamePlayerWhereInput) AddPredicates(predicates ...predicate.GamePlayer) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the GamePlayerWhereInput filter on the GamePlayerQuery builder.
func (i *GamePlayerWhereInput) Filter(q *GamePlayerQuery) (*GamePlayerQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyGamePlayerWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyGamePlayerWhereInput is returned in case the GamePlayerWhereInput is empty.
var ErrEmptyGamePlayerWhereInput = errors.New("codegen: empty predicate GamePlayerWhereInput")

// P returns a predicate for filtering gameplayers.
// An error is returned if the input is empty or invalid.
func (i *GamePlayerWhereInput) P() (predicate.GamePlayer, error) {
	var predicates []predicate.GamePlayer
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, gameplayer.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.GamePlayer, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, gameplayer.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.GamePlayer, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, gameplayer.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, gameplayer.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, gameplayer.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, gameplayer.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, gameplayer.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, gameplayer.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, gameplayer.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, gameplayer.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, gameplayer.IDLTE(*i.IDLTE))
	}
	if i.Kind != nil {
		predicates = append(predicates, gameplayer.KindEQ(*i.Kind))
	}
	if i.KindNEQ != nil {
		predicates = append(predicates, gameplayer.KindNEQ(*i.KindNEQ))
	}
	if len(i.KindIn) > 0 {
		predicates = append(predicates, gameplayer.KindIn(i.KindIn...))
	}
	if len(i.KindNotIn) > 0 {
		predicates = append(predicates, gameplayer.KindNotIn(i.KindNotIn...))
	}
	if i.Marker != nil {
		predicates = append(predicates, gameplayer.MarkerEQ(*i.Marker))
	}
	if i.MarkerNEQ != nil {
		predicates = append(predicates, gameplayer.MarkerNEQ(*i.MarkerNEQ))
	}
	if len(i.MarkerIn) > 0 {
		predicates = append(predicates, gameplayer.MarkerIn(i.MarkerIn...))
	}
	if len(i.MarkerNotIn) > 0 {
		predicates = append(predicates, gameplayer.MarkerNotIn(i.MarkerNotIn...))
	}
	if i.MarkerGT != nil {
		predicates = append(predicates, gameplayer.MarkerGT(*i.MarkerGT))
	}
	if i.MarkerGTE != nil {
		predicates = append(predicates, gameplayer.MarkerGTE(*i.MarkerGTE))
	}
	if i.MarkerLT != nil {
		predicates = append(predicates, gameplayer.MarkerLT(*i.MarkerLT))
	}
	if i.MarkerLTE != nil {
		predicates = append(predicates, gameplayer.MarkerLTE(*i.MarkerLTE))
	}
	if i.MarkerContains != nil {
		predicates = append(predicates, gameplayer.MarkerContains(*i.MarkerContains))
	}
	if i.MarkerHasPrefix != nil {
		predicates = append(predicates, gameplayer.MarkerHasPrefix(*i.MarkerHasPrefix))
	}
	if i.MarkerHasSuffix != nil {
		predicates = append(predicates, gameplayer.MarkerHasSuffix(*i.MarkerHasSuffix))
	}
	if i.MarkerEqualFold != nil {
		predicates = append(predicates, gameplayer.MarkerEqualFold(*i.MarkerEqualFold))
	}
	if i.MarkerContainsFold != nil {
		predicates = append(predicates, gameplayer.MarkerContainsFold(*i.MarkerContainsFold))
	}

	if i.HasUser != nil {
		p := gameplayer.HasUser()
		if !*i.HasUser {
			p = gameplayer.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasUserWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasUserWith))
		for _, w := range i.HasUserWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasUserWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, gameplayer.HasUserWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyGamePlayerWhereInput
	case 1:
		return predicates[0], nil
	default:
		return gameplayer.And(predicates...), nil
	}
}

// UserWhereInput represents a where input for filtering User queries.
type UserWhereInput struct {
	Predicates []predicate.User  `json:"-"`
	Not        *UserWhereInput   `json:"not,omitempty"`
	Or         []*UserWhereInput `json:"or,omitempty"`
	And        []*UserWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *int  `json:"id,omitempty"`
	IDNEQ   *int  `json:"idNEQ,omitempty"`
	IDIn    []int `json:"idIn,omitempty"`
	IDNotIn []int `json:"idNotIn,omitempty"`
	IDGT    *int  `json:"idGT,omitempty"`
	IDGTE   *int  `json:"idGTE,omitempty"`
	IDLT    *int  `json:"idLT,omitempty"`
	IDLTE   *int  `json:"idLTE,omitempty"`

	// "email" field predicates.
	Email             *string  `json:"email,omitempty"`
	EmailNEQ          *string  `json:"emailNEQ,omitempty"`
	EmailIn           []string `json:"emailIn,omitempty"`
	EmailNotIn        []string `json:"emailNotIn,omitempty"`
	EmailGT           *string  `json:"emailGT,omitempty"`
	EmailGTE          *string  `json:"emailGTE,omitempty"`
	EmailLT           *string  `json:"emailLT,omitempty"`
	EmailLTE          *string  `json:"emailLTE,omitempty"`
	EmailContains     *string  `json:"emailContains,omitempty"`
	EmailHasPrefix    *string  `json:"emailHasPrefix,omitempty"`
	EmailHasSuffix    *string  `json:"emailHasSuffix,omitempty"`
	EmailEqualFold    *string  `json:"emailEqualFold,omitempty"`
	EmailContainsFold *string  `json:"emailContainsFold,omitempty"`

	// "hashed_password" field predicates.
	HashedPassword             *string  `json:"hashedPassword,omitempty"`
	HashedPasswordNEQ          *string  `json:"hashedPasswordNEQ,omitempty"`
	HashedPasswordIn           []string `json:"hashedPasswordIn,omitempty"`
	HashedPasswordNotIn        []string `json:"hashedPasswordNotIn,omitempty"`
	HashedPasswordGT           *string  `json:"hashedPasswordGT,omitempty"`
	HashedPasswordGTE          *string  `json:"hashedPasswordGTE,omitempty"`
	HashedPasswordLT           *string  `json:"hashedPasswordLT,omitempty"`
	HashedPasswordLTE          *string  `json:"hashedPasswordLTE,omitempty"`
	HashedPasswordContains     *string  `json:"hashedPasswordContains,omitempty"`
	HashedPasswordHasPrefix    *string  `json:"hashedPasswordHasPrefix,omitempty"`
	HashedPasswordHasSuffix    *string  `json:"hashedPasswordHasSuffix,omitempty"`
	HashedPasswordEqualFold    *string  `json:"hashedPasswordEqualFold,omitempty"`
	HashedPasswordContainsFold *string  `json:"hashedPasswordContainsFold,omitempty"`

	// "friends" edge predicates.
	HasFriends     *bool             `json:"hasFriends,omitempty"`
	HasFriendsWith []*UserWhereInput `json:"hasFriendsWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *UserWhereInput) AddPredicates(predicates ...predicate.User) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the UserWhereInput filter on the UserQuery builder.
func (i *UserWhereInput) Filter(q *UserQuery) (*UserQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyUserWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyUserWhereInput is returned in case the UserWhereInput is empty.
var ErrEmptyUserWhereInput = errors.New("codegen: empty predicate UserWhereInput")

// P returns a predicate for filtering users.
// An error is returned if the input is empty or invalid.
func (i *UserWhereInput) P() (predicate.User, error) {
	var predicates []predicate.User
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, user.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.User, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, user.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.User, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, user.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, user.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, user.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, user.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, user.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, user.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, user.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, user.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, user.IDLTE(*i.IDLTE))
	}
	if i.Email != nil {
		predicates = append(predicates, user.EmailEQ(*i.Email))
	}
	if i.EmailNEQ != nil {
		predicates = append(predicates, user.EmailNEQ(*i.EmailNEQ))
	}
	if len(i.EmailIn) > 0 {
		predicates = append(predicates, user.EmailIn(i.EmailIn...))
	}
	if len(i.EmailNotIn) > 0 {
		predicates = append(predicates, user.EmailNotIn(i.EmailNotIn...))
	}
	if i.EmailGT != nil {
		predicates = append(predicates, user.EmailGT(*i.EmailGT))
	}
	if i.EmailGTE != nil {
		predicates = append(predicates, user.EmailGTE(*i.EmailGTE))
	}
	if i.EmailLT != nil {
		predicates = append(predicates, user.EmailLT(*i.EmailLT))
	}
	if i.EmailLTE != nil {
		predicates = append(predicates, user.EmailLTE(*i.EmailLTE))
	}
	if i.EmailContains != nil {
		predicates = append(predicates, user.EmailContains(*i.EmailContains))
	}
	if i.EmailHasPrefix != nil {
		predicates = append(predicates, user.EmailHasPrefix(*i.EmailHasPrefix))
	}
	if i.EmailHasSuffix != nil {
		predicates = append(predicates, user.EmailHasSuffix(*i.EmailHasSuffix))
	}
	if i.EmailEqualFold != nil {
		predicates = append(predicates, user.EmailEqualFold(*i.EmailEqualFold))
	}
	if i.EmailContainsFold != nil {
		predicates = append(predicates, user.EmailContainsFold(*i.EmailContainsFold))
	}
	if i.HashedPassword != nil {
		predicates = append(predicates, user.HashedPasswordEQ(*i.HashedPassword))
	}
	if i.HashedPasswordNEQ != nil {
		predicates = append(predicates, user.HashedPasswordNEQ(*i.HashedPasswordNEQ))
	}
	if len(i.HashedPasswordIn) > 0 {
		predicates = append(predicates, user.HashedPasswordIn(i.HashedPasswordIn...))
	}
	if len(i.HashedPasswordNotIn) > 0 {
		predicates = append(predicates, user.HashedPasswordNotIn(i.HashedPasswordNotIn...))
	}
	if i.HashedPasswordGT != nil {
		predicates = append(predicates, user.HashedPasswordGT(*i.HashedPasswordGT))
	}
	if i.HashedPasswordGTE != nil {
		predicates = append(predicates, user.HashedPasswordGTE(*i.HashedPasswordGTE))
	}
	if i.HashedPasswordLT != nil {
		predicates = append(predicates, user.HashedPasswordLT(*i.HashedPasswordLT))
	}
	if i.HashedPasswordLTE != nil {
		predicates = append(predicates, user.HashedPasswordLTE(*i.HashedPasswordLTE))
	}
	if i.HashedPasswordContains != nil {
		predicates = append(predicates, user.HashedPasswordContains(*i.HashedPasswordContains))
	}
	if i.HashedPasswordHasPrefix != nil {
		predicates = append(predicates, user.HashedPasswordHasPrefix(*i.HashedPasswordHasPrefix))
	}
	if i.HashedPasswordHasSuffix != nil {
		predicates = append(predicates, user.HashedPasswordHasSuffix(*i.HashedPasswordHasSuffix))
	}
	if i.HashedPasswordEqualFold != nil {
		predicates = append(predicates, user.HashedPasswordEqualFold(*i.HashedPasswordEqualFold))
	}
	if i.HashedPasswordContainsFold != nil {
		predicates = append(predicates, user.HashedPasswordContainsFold(*i.HashedPasswordContainsFold))
	}

	if i.HasFriends != nil {
		p := user.HasFriends()
		if !*i.HasFriends {
			p = user.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasFriendsWith) > 0 {
		with := make([]predicate.User, 0, len(i.HasFriendsWith))
		for _, w := range i.HasFriendsWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasFriendsWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, user.HasFriendsWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyUserWhereInput
	case 1:
		return predicates[0], nil
	default:
		return user.And(predicates...), nil
	}
}
