// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"puzzlr.gg/src/server/db/ent/codegen/game"
	"puzzlr.gg/src/server/db/ent/codegen/gameplayer"
	"puzzlr.gg/src/server/db/ent/codegen/predicate"
	"puzzlr.gg/src/server/db/ent/codegen/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetHashedPassword sets the "hashed_password" field.
func (_u *UserUpdate) SetHashedPassword(v string) *UserUpdate {
	_u.mutation.SetHashedPassword(v)
	return _u
}

// SetNillableHashedPassword sets the "hashed_password" field if the given value is not nil.
func (_u *UserUpdate) SetNillableHashedPassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetHashedPassword(*v)
	}
	return _u
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (_u *UserUpdate) AddGameIDs(ids ...int) *UserUpdate {
	_u.mutation.AddGameIDs(ids...)
	return _u
}

// AddGames adds the "games" edges to the Game entity.
func (_u *UserUpdate) AddGames(v ...*Game) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGameIDs(ids...)
}

// AddWonGameIDs adds the "won_games" edge to the Game entity by IDs.
func (_u *UserUpdate) AddWonGameIDs(ids ...int) *UserUpdate {
	_u.mutation.AddWonGameIDs(ids...)
	return _u
}

// AddWonGames adds the "won_games" edges to the Game entity.
func (_u *UserUpdate) AddWonGames(v ...*Game) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWonGameIDs(ids...)
}

// AddCurrentTurnGameIDs adds the "current_turn_games" edge to the Game entity by IDs.
func (_u *UserUpdate) AddCurrentTurnGameIDs(ids ...int) *UserUpdate {
	_u.mutation.AddCurrentTurnGameIDs(ids...)
	return _u
}

// AddCurrentTurnGames adds the "current_turn_games" edges to the Game entity.
func (_u *UserUpdate) AddCurrentTurnGames(v ...*Game) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCurrentTurnGameIDs(ids...)
}

// AddGamePlayerIDs adds the "game_player" edge to the GamePlayer entity by IDs.
func (_u *UserUpdate) AddGamePlayerIDs(ids ...int) *UserUpdate {
	_u.mutation.AddGamePlayerIDs(ids...)
	return _u
}

// AddGamePlayer adds the "game_player" edges to the GamePlayer entity.
func (_u *UserUpdate) AddGamePlayer(v ...*GamePlayer) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGamePlayerIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearGames clears all "games" edges to the Game entity.
func (_u *UserUpdate) ClearGames() *UserUpdate {
	_u.mutation.ClearGames()
	return _u
}

// RemoveGameIDs removes the "games" edge to Game entities by IDs.
func (_u *UserUpdate) RemoveGameIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveGameIDs(ids...)
	return _u
}

// RemoveGames removes "games" edges to Game entities.
func (_u *UserUpdate) RemoveGames(v ...*Game) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGameIDs(ids...)
}

// ClearWonGames clears all "won_games" edges to the Game entity.
func (_u *UserUpdate) ClearWonGames() *UserUpdate {
	_u.mutation.ClearWonGames()
	return _u
}

// RemoveWonGameIDs removes the "won_games" edge to Game entities by IDs.
func (_u *UserUpdate) RemoveWonGameIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveWonGameIDs(ids...)
	return _u
}

// RemoveWonGames removes "won_games" edges to Game entities.
func (_u *UserUpdate) RemoveWonGames(v ...*Game) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWonGameIDs(ids...)
}

// ClearCurrentTurnGames clears all "current_turn_games" edges to the Game entity.
func (_u *UserUpdate) ClearCurrentTurnGames() *UserUpdate {
	_u.mutation.ClearCurrentTurnGames()
	return _u
}

// RemoveCurrentTurnGameIDs removes the "current_turn_games" edge to Game entities by IDs.
func (_u *UserUpdate) RemoveCurrentTurnGameIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveCurrentTurnGameIDs(ids...)
	return _u
}

// RemoveCurrentTurnGames removes "current_turn_games" edges to Game entities.
func (_u *UserUpdate) RemoveCurrentTurnGames(v ...*Game) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCurrentTurnGameIDs(ids...)
}

// ClearGamePlayer clears all "game_player" edges to the GamePlayer entity.
func (_u *UserUpdate) ClearGamePlayer() *UserUpdate {
	_u.mutation.ClearGamePlayer()
	return _u
}

// RemoveGamePlayerIDs removes the "game_player" edge to GamePlayer entities by IDs.
func (_u *UserUpdate) RemoveGamePlayerIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveGamePlayerIDs(ids...)
	return _u
}

// RemoveGamePlayer removes "game_player" edges to GamePlayer entities.
func (_u *UserUpdate) RemoveGamePlayer(v ...*GamePlayer) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGamePlayerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`codegen: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashedPassword(); ok {
		if err := user.HashedPasswordValidator(v); err != nil {
			return &ValidationError{Name: "hashed_password", err: fmt.Errorf(`codegen: validator failed for field "User.hashed_password": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashedPassword(); ok {
		_spec.SetField(user.FieldHashedPassword, field.TypeString, value)
	}
	if _u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.GamesTable,
			Columns: user.GamesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamesIDs(); len(nodes) > 0 && !_u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.GamesTable,
			Columns: user.GamesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.GamesTable,
			Columns: user.GamesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WonGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WonGamesTable,
			Columns: []string{user.WonGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWonGamesIDs(); len(nodes) > 0 && !_u.mutation.WonGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WonGamesTable,
			Columns: []string{user.WonGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WonGamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WonGamesTable,
			Columns: []string{user.WonGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentTurnGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CurrentTurnGamesTable,
			Columns: []string{user.CurrentTurnGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCurrentTurnGamesIDs(); len(nodes) > 0 && !_u.mutation.CurrentTurnGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CurrentTurnGamesTable,
			Columns: []string{user.CurrentTurnGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentTurnGamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CurrentTurnGamesTable,
			Columns: []string{user.CurrentTurnGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.GamePlayerTable,
			Columns: []string{user.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamePlayerIDs(); len(nodes) > 0 && !_u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.GamePlayerTable,
			Columns: []string{user.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamePlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.GamePlayerTable,
			Columns: []string{user.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetHashedPassword sets the "hashed_password" field.
func (_u *UserUpdateOne) SetHashedPassword(v string) *UserUpdateOne {
	_u.mutation.SetHashedPassword(v)
	return _u
}

// SetNillableHashedPassword sets the "hashed_password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableHashedPassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetHashedPassword(*v)
	}
	return _u
}

// AddGameIDs adds the "games" edge to the Game entity by IDs.
func (_u *UserUpdateOne) AddGameIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddGameIDs(ids...)
	return _u
}

// AddGames adds the "games" edges to the Game entity.
func (_u *UserUpdateOne) AddGames(v ...*Game) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGameIDs(ids...)
}

// AddWonGameIDs adds the "won_games" edge to the Game entity by IDs.
func (_u *UserUpdateOne) AddWonGameIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddWonGameIDs(ids...)
	return _u
}

// AddWonGames adds the "won_games" edges to the Game entity.
func (_u *UserUpdateOne) AddWonGames(v ...*Game) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWonGameIDs(ids...)
}

// AddCurrentTurnGameIDs adds the "current_turn_games" edge to the Game entity by IDs.
func (_u *UserUpdateOne) AddCurrentTurnGameIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddCurrentTurnGameIDs(ids...)
	return _u
}

// AddCurrentTurnGames adds the "current_turn_games" edges to the Game entity.
func (_u *UserUpdateOne) AddCurrentTurnGames(v ...*Game) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCurrentTurnGameIDs(ids...)
}

// AddGamePlayerIDs adds the "game_player" edge to the GamePlayer entity by IDs.
func (_u *UserUpdateOne) AddGamePlayerIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddGamePlayerIDs(ids...)
	return _u
}

// AddGamePlayer adds the "game_player" edges to the GamePlayer entity.
func (_u *UserUpdateOne) AddGamePlayer(v ...*GamePlayer) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGamePlayerIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearGames clears all "games" edges to the Game entity.
func (_u *UserUpdateOne) ClearGames() *UserUpdateOne {
	_u.mutation.ClearGames()
	return _u
}

// RemoveGameIDs removes the "games" edge to Game entities by IDs.
func (_u *UserUpdateOne) RemoveGameIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveGameIDs(ids...)
	return _u
}

// RemoveGames removes "games" edges to Game entities.
func (_u *UserUpdateOne) RemoveGames(v ...*Game) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGameIDs(ids...)
}

// ClearWonGames clears all "won_games" edges to the Game entity.
func (_u *UserUpdateOne) ClearWonGames() *UserUpdateOne {
	_u.mutation.ClearWonGames()
	return _u
}

// RemoveWonGameIDs removes the "won_games" edge to Game entities by IDs.
func (_u *UserUpdateOne) RemoveWonGameIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveWonGameIDs(ids...)
	return _u
}

// RemoveWonGames removes "won_games" edges to Game entities.
func (_u *UserUpdateOne) RemoveWonGames(v ...*Game) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWonGameIDs(ids...)
}

// ClearCurrentTurnGames clears all "current_turn_games" edges to the Game entity.
func (_u *UserUpdateOne) ClearCurrentTurnGames() *UserUpdateOne {
	_u.mutation.ClearCurrentTurnGames()
	return _u
}

// RemoveCurrentTurnGameIDs removes the "current_turn_games" edge to Game entities by IDs.
func (_u *UserUpdateOne) RemoveCurrentTurnGameIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveCurrentTurnGameIDs(ids...)
	return _u
}

// RemoveCurrentTurnGames removes "current_turn_games" edges to Game entities.
func (_u *UserUpdateOne) RemoveCurrentTurnGames(v ...*Game) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCurrentTurnGameIDs(ids...)
}

// ClearGamePlayer clears all "game_player" edges to the GamePlayer entity.
func (_u *UserUpdateOne) ClearGamePlayer() *UserUpdateOne {
	_u.mutation.ClearGamePlayer()
	return _u
}

// RemoveGamePlayerIDs removes the "game_player" edge to GamePlayer entities by IDs.
func (_u *UserUpdateOne) RemoveGamePlayerIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveGamePlayerIDs(ids...)
	return _u
}

// RemoveGamePlayer removes "game_player" edges to GamePlayer entities.
func (_u *UserUpdateOne) RemoveGamePlayer(v ...*GamePlayer) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGamePlayerIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`codegen: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HashedPassword(); ok {
		if err := user.HashedPasswordValidator(v); err != nil {
			return &ValidationError{Name: "hashed_password", err: fmt.Errorf(`codegen: validator failed for field "User.hashed_password": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`codegen: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("codegen: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.HashedPassword(); ok {
		_spec.SetField(user.FieldHashedPassword, field.TypeString, value)
	}
	if _u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.GamesTable,
			Columns: user.GamesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamesIDs(); len(nodes) > 0 && !_u.mutation.GamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.GamesTable,
			Columns: user.GamesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.GamesTable,
			Columns: user.GamesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WonGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WonGamesTable,
			Columns: []string{user.WonGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWonGamesIDs(); len(nodes) > 0 && !_u.mutation.WonGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WonGamesTable,
			Columns: []string{user.WonGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WonGamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WonGamesTable,
			Columns: []string{user.WonGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentTurnGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CurrentTurnGamesTable,
			Columns: []string{user.CurrentTurnGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCurrentTurnGamesIDs(); len(nodes) > 0 && !_u.mutation.CurrentTurnGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CurrentTurnGamesTable,
			Columns: []string{user.CurrentTurnGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentTurnGamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CurrentTurnGamesTable,
			Columns: []string{user.CurrentTurnGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.GamePlayerTable,
			Columns: []string{user.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGamePlayerIDs(); len(nodes) > 0 && !_u.mutation.GamePlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.GamePlayerTable,
			Columns: []string{user.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GamePlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.GamePlayerTable,
			Columns: []string{user.GamePlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameplayer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
