// Code generated by ent, DO NOT EDIT.

package codegen

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"puzzlr.gg/src/server/db/ent/codegen/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// HashedPassword holds the value of the "hashed_password" field.
	HashedPassword string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// GamePlayers holds the value of the game_players edge.
	GamePlayers []*GamePlayer `json:"game_players,omitempty"`
	// Friends holds the value of the friends edge.
	Friends []*User `json:"friends,omitempty"`
	// SentFriendRequests holds the value of the sent_friend_requests edge.
	SentFriendRequests []*FriendRequest `json:"sent_friend_requests,omitempty"`
	// ReceivedFriendRequests holds the value of the received_friend_requests edge.
	ReceivedFriendRequests []*FriendRequest `json:"received_friend_requests,omitempty"`
	// Friendships holds the value of the friendships edge.
	Friendships []*Friendship `json:"friendships,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedGamePlayers            map[string][]*GamePlayer
	namedFriends                map[string][]*User
	namedSentFriendRequests     map[string][]*FriendRequest
	namedReceivedFriendRequests map[string][]*FriendRequest
	namedFriendships            map[string][]*Friendship
}

// GamePlayersOrErr returns the GamePlayers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) GamePlayersOrErr() ([]*GamePlayer, error) {
	if e.loadedTypes[0] {
		return e.GamePlayers, nil
	}
	return nil, &NotLoadedError{edge: "game_players"}
}

// FriendsOrErr returns the Friends value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FriendsOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.Friends, nil
	}
	return nil, &NotLoadedError{edge: "friends"}
}

// SentFriendRequestsOrErr returns the SentFriendRequests value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SentFriendRequestsOrErr() ([]*FriendRequest, error) {
	if e.loadedTypes[2] {
		return e.SentFriendRequests, nil
	}
	return nil, &NotLoadedError{edge: "sent_friend_requests"}
}

// ReceivedFriendRequestsOrErr returns the ReceivedFriendRequests value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ReceivedFriendRequestsOrErr() ([]*FriendRequest, error) {
	if e.loadedTypes[3] {
		return e.ReceivedFriendRequests, nil
	}
	return nil, &NotLoadedError{edge: "received_friend_requests"}
}

// FriendshipsOrErr returns the Friendships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FriendshipsOrErr() ([]*Friendship, error) {
	if e.loadedTypes[4] {
		return e.Friendships, nil
	}
	return nil, &NotLoadedError{edge: "friendships"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail, user.FieldHashedPassword:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldHashedPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hashed_password", values[i])
			} else if value.Valid {
				_m.HashedPassword = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGamePlayers queries the "game_players" edge of the User entity.
func (_m *User) QueryGamePlayers() *GamePlayerQuery {
	return NewUserClient(_m.config).QueryGamePlayers(_m)
}

// QueryFriends queries the "friends" edge of the User entity.
func (_m *User) QueryFriends() *UserQuery {
	return NewUserClient(_m.config).QueryFriends(_m)
}

// QuerySentFriendRequests queries the "sent_friend_requests" edge of the User entity.
func (_m *User) QuerySentFriendRequests() *FriendRequestQuery {
	return NewUserClient(_m.config).QuerySentFriendRequests(_m)
}

// QueryReceivedFriendRequests queries the "received_friend_requests" edge of the User entity.
func (_m *User) QueryReceivedFriendRequests() *FriendRequestQuery {
	return NewUserClient(_m.config).QueryReceivedFriendRequests(_m)
}

// QueryFriendships queries the "friendships" edge of the User entity.
func (_m *User) QueryFriendships() *FriendshipQuery {
	return NewUserClient(_m.config).QueryFriendships(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("codegen: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("hashed_password=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// NamedGamePlayers returns the GamePlayers named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *User) NamedGamePlayers(name string) ([]*GamePlayer, error) {
	if _m.Edges.namedGamePlayers == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedGamePlayers[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *User) appendNamedGamePlayers(name string, edges ...*GamePlayer) {
	if _m.Edges.namedGamePlayers == nil {
		_m.Edges.namedGamePlayers = make(map[string][]*GamePlayer)
	}
	if len(edges) == 0 {
		_m.Edges.namedGamePlayers[name] = []*GamePlayer{}
	} else {
		_m.Edges.namedGamePlayers[name] = append(_m.Edges.namedGamePlayers[name], edges...)
	}
}

// NamedFriends returns the Friends named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *User) NamedFriends(name string) ([]*User, error) {
	if _m.Edges.namedFriends == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedFriends[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *User) appendNamedFriends(name string, edges ...*User) {
	if _m.Edges.namedFriends == nil {
		_m.Edges.namedFriends = make(map[string][]*User)
	}
	if len(edges) == 0 {
		_m.Edges.namedFriends[name] = []*User{}
	} else {
		_m.Edges.namedFriends[name] = append(_m.Edges.namedFriends[name], edges...)
	}
}

// NamedSentFriendRequests returns the SentFriendRequests named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *User) NamedSentFriendRequests(name string) ([]*FriendRequest, error) {
	if _m.Edges.namedSentFriendRequests == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedSentFriendRequests[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *User) appendNamedSentFriendRequests(name string, edges ...*FriendRequest) {
	if _m.Edges.namedSentFriendRequests == nil {
		_m.Edges.namedSentFriendRequests = make(map[string][]*FriendRequest)
	}
	if len(edges) == 0 {
		_m.Edges.namedSentFriendRequests[name] = []*FriendRequest{}
	} else {
		_m.Edges.namedSentFriendRequests[name] = append(_m.Edges.namedSentFriendRequests[name], edges...)
	}
}

// NamedReceivedFriendRequests returns the ReceivedFriendRequests named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *User) NamedReceivedFriendRequests(name string) ([]*FriendRequest, error) {
	if _m.Edges.namedReceivedFriendRequests == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedReceivedFriendRequests[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *User) appendNamedReceivedFriendRequests(name string, edges ...*FriendRequest) {
	if _m.Edges.namedReceivedFriendRequests == nil {
		_m.Edges.namedReceivedFriendRequests = make(map[string][]*FriendRequest)
	}
	if len(edges) == 0 {
		_m.Edges.namedReceivedFriendRequests[name] = []*FriendRequest{}
	} else {
		_m.Edges.namedReceivedFriendRequests[name] = append(_m.Edges.namedReceivedFriendRequests[name], edges...)
	}
}

// NamedFriendships returns the Friendships named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *User) NamedFriendships(name string) ([]*Friendship, error) {
	if _m.Edges.namedFriendships == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedFriendships[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *User) appendNamedFriendships(name string, edges ...*Friendship) {
	if _m.Edges.namedFriendships == nil {
		_m.Edges.namedFriendships = make(map[string][]*Friendship)
	}
	if len(edges) == 0 {
		_m.Edges.namedFriendships[name] = []*Friendship{}
	} else {
		_m.Edges.namedFriendships[name] = append(_m.Edges.namedFriendships[name], edges...)
	}
}

// Users is a parsable slice of User.
type Users []*User
