// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldHashedPassword holds the string denoting the hashed_password field in the database.
	FieldHashedPassword = "hashed_password"
	// EdgeGamePlayers holds the string denoting the game_players edge name in mutations.
	EdgeGamePlayers = "game_players"
	// EdgeFriends holds the string denoting the friends edge name in mutations.
	EdgeFriends = "friends"
	// EdgeSentFriendRequests holds the string denoting the sent_friend_requests edge name in mutations.
	EdgeSentFriendRequests = "sent_friend_requests"
	// EdgeReceivedFriendRequests holds the string denoting the received_friend_requests edge name in mutations.
	EdgeReceivedFriendRequests = "received_friend_requests"
	// EdgeFriendships holds the string denoting the friendships edge name in mutations.
	EdgeFriendships = "friendships"
	// Table holds the table name of the user in the database.
	Table = "users"
	// GamePlayersTable is the table that holds the game_players relation/edge.
	GamePlayersTable = "game_players"
	// GamePlayersInverseTable is the table name for the GamePlayer entity.
	// It exists in this package in order to avoid circular dependency with the "gameplayer" package.
	GamePlayersInverseTable = "game_players"
	// GamePlayersColumn is the table column denoting the game_players relation/edge.
	GamePlayersColumn = "user_id"
	// FriendsTable is the table that holds the friends relation/edge. The primary key declared below.
	FriendsTable = "friendships"
	// SentFriendRequestsTable is the table that holds the sent_friend_requests relation/edge.
	SentFriendRequestsTable = "friend_requests"
	// SentFriendRequestsInverseTable is the table name for the FriendRequest entity.
	// It exists in this package in order to avoid circular dependency with the "friendrequest" package.
	SentFriendRequestsInverseTable = "friend_requests"
	// SentFriendRequestsColumn is the table column denoting the sent_friend_requests relation/edge.
	SentFriendRequestsColumn = "requester_id"
	// ReceivedFriendRequestsTable is the table that holds the received_friend_requests relation/edge.
	ReceivedFriendRequestsTable = "friend_requests"
	// ReceivedFriendRequestsInverseTable is the table name for the FriendRequest entity.
	// It exists in this package in order to avoid circular dependency with the "friendrequest" package.
	ReceivedFriendRequestsInverseTable = "friend_requests"
	// ReceivedFriendRequestsColumn is the table column denoting the received_friend_requests relation/edge.
	ReceivedFriendRequestsColumn = "recipient_id"
	// FriendshipsTable is the table that holds the friendships relation/edge.
	FriendshipsTable = "friendships"
	// FriendshipsInverseTable is the table name for the Friendship entity.
	// It exists in this package in order to avoid circular dependency with the "friendship" package.
	FriendshipsInverseTable = "friendships"
	// FriendshipsColumn is the table column denoting the friendships relation/edge.
	FriendshipsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldHashedPassword,
}

var (
	// FriendsPrimaryKey and FriendsColumn2 are the table columns denoting the
	// primary key for the friends relation (M2M).
	FriendsPrimaryKey = []string{"user_id", "friend_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "puzzlr.gg/src/server/db/ent/codegen/runtime"
var (
	Hooks  [2]ent.Hook
	Policy ent.Policy
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// HashedPasswordValidator is a validator for the "hashed_password" field. It is called by the builders before save.
	HashedPasswordValidator func(string) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByHashedPassword orders the results by the hashed_password field.
func ByHashedPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashedPassword, opts...).ToFunc()
}

// ByGamePlayersCount orders the results by game_players count.
func ByGamePlayersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGamePlayersStep(), opts...)
	}
}

// ByGamePlayers orders the results by game_players terms.
func ByGamePlayers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGamePlayersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFriendsCount orders the results by friends count.
func ByFriendsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFriendsStep(), opts...)
	}
}

// ByFriends orders the results by friends terms.
func ByFriends(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFriendsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySentFriendRequestsCount orders the results by sent_friend_requests count.
func BySentFriendRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSentFriendRequestsStep(), opts...)
	}
}

// BySentFriendRequests orders the results by sent_friend_requests terms.
func BySentFriendRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSentFriendRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReceivedFriendRequestsCount orders the results by received_friend_requests count.
func ByReceivedFriendRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReceivedFriendRequestsStep(), opts...)
	}
}

// ByReceivedFriendRequests orders the results by received_friend_requests terms.
func ByReceivedFriendRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReceivedFriendRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFriendshipsCount orders the results by friendships count.
func ByFriendshipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFriendshipsStep(), opts...)
	}
}

// ByFriendships orders the results by friendships terms.
func ByFriendships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFriendshipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGamePlayersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GamePlayersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, GamePlayersTable, GamePlayersColumn),
	)
}
func newFriendsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, FriendsTable, FriendsPrimaryKey...),
	)
}
func newSentFriendRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SentFriendRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, SentFriendRequestsTable, SentFriendRequestsColumn),
	)
}
func newReceivedFriendRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReceivedFriendRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ReceivedFriendRequestsTable, ReceivedFriendRequestsColumn),
	)
}
func newFriendshipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FriendshipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, FriendshipsTable, FriendshipsColumn),
	)
}
