// Code generated by ent, DO NOT EDIT.

package privacy

import (
	"context"

	"puzzlr.gg/src/server/db/ent/codegen"

	"entgo.io/ent/privacy"
)

var (
	// Allow may be returned by rules to indicate that the policy
	// evaluation should terminate with allow decision.
	Allow = privacy.Allow

	// Deny may be returned by rules to indicate that the policy
	// evaluation should terminate with deny decision.
	Deny = privacy.Deny

	// Skip may be returned by rules to indicate that the policy
	// evaluation should continue to the next rule.
	Skip = privacy.Skip
)

// Allowf returns a formatted wrapped Allow decision.
func Allowf(format string, a ...any) error {
	return privacy.Allowf(format, a...)
}

// Denyf returns a formatted wrapped Deny decision.
func Denyf(format string, a ...any) error {
	return privacy.Denyf(format, a...)
}

// Skipf returns a formatted wrapped Skip decision.
func Skipf(format string, a ...any) error {
	return privacy.Skipf(format, a...)
}

// DecisionContext creates a new context from the given parent context with
// a policy decision attach to it.
func DecisionContext(parent context.Context, decision error) context.Context {
	return privacy.DecisionContext(parent, decision)
}

// DecisionFromContext retrieves the policy decision from the context.
func DecisionFromContext(ctx context.Context) (error, bool) {
	return privacy.DecisionFromContext(ctx)
}

type (
	// Policy groups query and mutation policies.
	Policy = privacy.Policy

	// QueryRule defines the interface deciding whether a
	// query is allowed and optionally modify it.
	QueryRule = privacy.QueryRule
	// QueryPolicy combines multiple query rules into a single policy.
	QueryPolicy = privacy.QueryPolicy

	// MutationRule defines the interface which decides whether a
	// mutation is allowed and optionally modifies it.
	MutationRule = privacy.MutationRule
	// MutationPolicy combines multiple mutation rules into a single policy.
	MutationPolicy = privacy.MutationPolicy
	// MutationRuleFunc type is an adapter which allows the use of
	// ordinary functions as mutation rules.
	MutationRuleFunc = privacy.MutationRuleFunc

	// QueryMutationRule is an interface which groups query and mutation rules.
	QueryMutationRule = privacy.QueryMutationRule
)

// QueryRuleFunc type is an adapter to allow the use of
// ordinary functions as query rules.
type QueryRuleFunc func(context.Context, codegen.Query) error

// Eval returns f(ctx, q).
func (f QueryRuleFunc) EvalQuery(ctx context.Context, q codegen.Query) error {
	return f(ctx, q)
}

// AlwaysAllowRule returns a rule that returns an allow decision.
func AlwaysAllowRule() QueryMutationRule {
	return privacy.AlwaysAllowRule()
}

// AlwaysDenyRule returns a rule that returns a deny decision.
func AlwaysDenyRule() QueryMutationRule {
	return privacy.AlwaysDenyRule()
}

// ContextQueryMutationRule creates a query/mutation rule from a context eval func.
func ContextQueryMutationRule(eval func(context.Context) error) QueryMutationRule {
	return privacy.ContextQueryMutationRule(eval)
}

// OnMutationOperation evaluates the given rule only on a given mutation operation.
func OnMutationOperation(rule MutationRule, op codegen.Op) MutationRule {
	return privacy.OnMutationOperation(rule, op)
}

// DenyMutationOperationRule returns a rule denying specified mutation operation.
func DenyMutationOperationRule(op codegen.Op) MutationRule {
	rule := MutationRuleFunc(func(_ context.Context, m codegen.Mutation) error {
		return Denyf("codegen/privacy: operation %s is not allowed", m.Op())
	})
	return OnMutationOperation(rule, op)
}

// The FriendRequestQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type FriendRequestQueryRuleFunc func(context.Context, *codegen.FriendRequestQuery) error

// EvalQuery return f(ctx, q).
func (f FriendRequestQueryRuleFunc) EvalQuery(ctx context.Context, q codegen.Query) error {
	if q, ok := q.(*codegen.FriendRequestQuery); ok {
		return f(ctx, q)
	}
	return Denyf("codegen/privacy: unexpected query type %T, expect *codegen.FriendRequestQuery", q)
}

// The FriendRequestMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type FriendRequestMutationRuleFunc func(context.Context, *codegen.FriendRequestMutation) error

// EvalMutation calls f(ctx, m).
func (f FriendRequestMutationRuleFunc) EvalMutation(ctx context.Context, m codegen.Mutation) error {
	if m, ok := m.(*codegen.FriendRequestMutation); ok {
		return f(ctx, m)
	}
	return Denyf("codegen/privacy: unexpected mutation type %T, expect *codegen.FriendRequestMutation", m)
}

// The FriendshipQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type FriendshipQueryRuleFunc func(context.Context, *codegen.FriendshipQuery) error

// EvalQuery return f(ctx, q).
func (f FriendshipQueryRuleFunc) EvalQuery(ctx context.Context, q codegen.Query) error {
	if q, ok := q.(*codegen.FriendshipQuery); ok {
		return f(ctx, q)
	}
	return Denyf("codegen/privacy: unexpected query type %T, expect *codegen.FriendshipQuery", q)
}

// The FriendshipMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type FriendshipMutationRuleFunc func(context.Context, *codegen.FriendshipMutation) error

// EvalMutation calls f(ctx, m).
func (f FriendshipMutationRuleFunc) EvalMutation(ctx context.Context, m codegen.Mutation) error {
	if m, ok := m.(*codegen.FriendshipMutation); ok {
		return f(ctx, m)
	}
	return Denyf("codegen/privacy: unexpected mutation type %T, expect *codegen.FriendshipMutation", m)
}

// The GameQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type GameQueryRuleFunc func(context.Context, *codegen.GameQuery) error

// EvalQuery return f(ctx, q).
func (f GameQueryRuleFunc) EvalQuery(ctx context.Context, q codegen.Query) error {
	if q, ok := q.(*codegen.GameQuery); ok {
		return f(ctx, q)
	}
	return Denyf("codegen/privacy: unexpected query type %T, expect *codegen.GameQuery", q)
}

// The GameMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type GameMutationRuleFunc func(context.Context, *codegen.GameMutation) error

// EvalMutation calls f(ctx, m).
func (f GameMutationRuleFunc) EvalMutation(ctx context.Context, m codegen.Mutation) error {
	if m, ok := m.(*codegen.GameMutation); ok {
		return f(ctx, m)
	}
	return Denyf("codegen/privacy: unexpected mutation type %T, expect *codegen.GameMutation", m)
}

// The GamePlayerQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type GamePlayerQueryRuleFunc func(context.Context, *codegen.GamePlayerQuery) error

// EvalQuery return f(ctx, q).
func (f GamePlayerQueryRuleFunc) EvalQuery(ctx context.Context, q codegen.Query) error {
	if q, ok := q.(*codegen.GamePlayerQuery); ok {
		return f(ctx, q)
	}
	return Denyf("codegen/privacy: unexpected query type %T, expect *codegen.GamePlayerQuery", q)
}

// The GamePlayerMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type GamePlayerMutationRuleFunc func(context.Context, *codegen.GamePlayerMutation) error

// EvalMutation calls f(ctx, m).
func (f GamePlayerMutationRuleFunc) EvalMutation(ctx context.Context, m codegen.Mutation) error {
	if m, ok := m.(*codegen.GamePlayerMutation); ok {
		return f(ctx, m)
	}
	return Denyf("codegen/privacy: unexpected mutation type %T, expect *codegen.GamePlayerMutation", m)
}

// The UserQueryRuleFunc type is an adapter to allow the use of ordinary
// functions as a query rule.
type UserQueryRuleFunc func(context.Context, *codegen.UserQuery) error

// EvalQuery return f(ctx, q).
func (f UserQueryRuleFunc) EvalQuery(ctx context.Context, q codegen.Query) error {
	if q, ok := q.(*codegen.UserQuery); ok {
		return f(ctx, q)
	}
	return Denyf("codegen/privacy: unexpected query type %T, expect *codegen.UserQuery", q)
}

// The UserMutationRuleFunc type is an adapter to allow the use of ordinary
// functions as a mutation rule.
type UserMutationRuleFunc func(context.Context, *codegen.UserMutation) error

// EvalMutation calls f(ctx, m).
func (f UserMutationRuleFunc) EvalMutation(ctx context.Context, m codegen.Mutation) error {
	if m, ok := m.(*codegen.UserMutation); ok {
		return f(ctx, m)
	}
	return Denyf("codegen/privacy: unexpected mutation type %T, expect *codegen.UserMutation", m)
}
