// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"time"

	"puzzlr.gg/src/server/db/ent/codegen/friendrequest"
	"puzzlr.gg/src/server/db/ent/codegen/friendship"
	"puzzlr.gg/src/server/db/ent/codegen/game"
	"puzzlr.gg/src/server/db/ent/codegen/gameplayer"
	"puzzlr.gg/src/server/db/ent/codegen/user"
	"puzzlr.gg/src/server/db/ent/schema"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	friendrequestMixin := schema.FriendRequest{}.Mixin()
	friendrequest.Policy = privacy.NewPolicies(schema.FriendRequest{})
	friendrequest.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := friendrequest.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	friendrequestHooks := schema.FriendRequest{}.Hooks()

	friendrequest.Hooks[1] = friendrequestHooks[0]
	friendrequestMixinFields0 := friendrequestMixin[0].Fields()
	_ = friendrequestMixinFields0
	friendrequestFields := schema.FriendRequest{}.Fields()
	_ = friendrequestFields
	// friendrequestDescCreateTime is the schema descriptor for create_time field.
	friendrequestDescCreateTime := friendrequestMixinFields0[0].Descriptor()
	// friendrequest.DefaultCreateTime holds the default value on creation for the create_time field.
	friendrequest.DefaultCreateTime = friendrequestDescCreateTime.Default.(func() time.Time)
	// friendrequestDescUpdateTime is the schema descriptor for update_time field.
	friendrequestDescUpdateTime := friendrequestMixinFields0[1].Descriptor()
	// friendrequest.DefaultUpdateTime holds the default value on creation for the update_time field.
	friendrequest.DefaultUpdateTime = friendrequestDescUpdateTime.Default.(func() time.Time)
	// friendrequest.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	friendrequest.UpdateDefaultUpdateTime = friendrequestDescUpdateTime.UpdateDefault.(func() time.Time)
	friendshipHooks := schema.Friendship{}.Hooks()
	friendship.Hooks[0] = friendshipHooks[0]
	gameMixin := schema.Game{}.Mixin()
	gameHooks := schema.Game{}.Hooks()
	game.Hooks[0] = gameHooks[0]
	game.Hooks[1] = gameHooks[1]
	game.Hooks[2] = gameHooks[2]
	game.Hooks[3] = gameHooks[3]
	game.Hooks[4] = gameHooks[4]
	gameMixinFields0 := gameMixin[0].Fields()
	_ = gameMixinFields0
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescCreateTime is the schema descriptor for create_time field.
	gameDescCreateTime := gameMixinFields0[0].Descriptor()
	// game.DefaultCreateTime holds the default value on creation for the create_time field.
	game.DefaultCreateTime = gameDescCreateTime.Default.(func() time.Time)
	// gameDescUpdateTime is the schema descriptor for update_time field.
	gameDescUpdateTime := gameMixinFields0[1].Descriptor()
	// game.DefaultUpdateTime holds the default value on creation for the update_time field.
	game.DefaultUpdateTime = gameDescUpdateTime.Default.(func() time.Time)
	// game.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	game.UpdateDefaultUpdateTime = gameDescUpdateTime.UpdateDefault.(func() time.Time)
	gameplayerHooks := schema.GamePlayer{}.Hooks()
	gameplayer.Hooks[0] = gameplayerHooks[0]
	gameplayer.Hooks[1] = gameplayerHooks[1]
	gameplayerFields := schema.GamePlayer{}.Fields()
	_ = gameplayerFields
	// gameplayerDescMarker is the schema descriptor for marker field.
	gameplayerDescMarker := gameplayerFields[2].Descriptor()
	// gameplayer.MarkerValidator is a validator for the "marker" field. It is called by the builders before save.
	gameplayer.MarkerValidator = gameplayerDescMarker.Validators[0].(func(string) error)
	user.Policy = privacy.NewPolicies(schema.User{})
	user.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := user.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	userHooks := schema.User{}.Hooks()

	user.Hooks[1] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescHashedPassword is the schema descriptor for hashed_password field.
	userDescHashedPassword := userFields[1].Descriptor()
	// user.HashedPasswordValidator is a validator for the "hashed_password" field. It is called by the builders before save.
	user.HashedPasswordValidator = userDescHashedPassword.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
